package sys.modelo;
// Generated 17/09/2023 23:22:20 by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer codEmpleado;
     private String nombre;
     private String apellido;
     private String cargo;
     private int telefono;
     private String direccion;

    public Empleado() {
    }

	
    public Empleado(String nombre, String apellido, String cargo, int telefono) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.cargo = cargo;
        this.telefono = telefono;
    }
    public Empleado(String nombre, String apellido, String cargo, int telefono, String direccion) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.cargo = cargo;
       this.telefono = telefono;
       this.direccion = direccion;
    }
   
    public Integer getCodEmpleado() {
        return this.codEmpleado;
    }
    
    public void setCodEmpleado(Integer codEmpleado) {
        this.codEmpleado = codEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


