package sys.modelo;
// Generated 17/09/2023 23:22:20 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer codUsuario;
     private String nombreUsuario;
     private String password;
     private int codVendedor;

    public Usuario() {
    }

    public Usuario(String nombreUsuario, String password, int codVendedor) {
       this.nombreUsuario = nombreUsuario;
       this.password = password;
       this.codVendedor = codVendedor;
    }
   
    public Integer getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(Integer codUsuario) {
        this.codUsuario = codUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getCodVendedor() {
        return this.codVendedor;
    }
    
    public void setCodVendedor(int codVendedor) {
        this.codVendedor = codVendedor;
    }




}


